### PR TITLE
Standstill recognition via standard deviation of face roll, pitch, yaw, distance

### PR DESCRIPTION
**Pull request by Jaszkowic**
Checking standard deviation of face roll, pitch, yaw and distance to be less than a predefined threshold.

Must be below that threshold for > 2 sec to trigger photo.

### CODE REVIEW

**Comment by ff6347** [comment]
Very nice. Can you move the MathUtils.ts into the `lib/utils/math.ts`.

I would actually prefer lowercase file names and having all the additional code besides components in the lib folder.

**Comment by ff6347** [comment]
FYI. Deploys will fail since we can't deploy on vercel. I will address that ASAP

**Comment by Jaszkowic** [comment]
For testing, try around moving: Top left will say "Stay still". When you stay still, it will say "Stay like this". After 2 seconds of staying still, it would trigger the prompt / image generation (right now, for testing, it only says "Photo triggered".

In next iterations, I will make the UI for this pretty.

**Comment by Jaszkowic** [comment]
Bildschirmfoto 2023-06-07 um 11 37 25
Bildschirmfoto 2023-06-07 um 11 37 34

**Pull request merged**
